### ISSUE TITLE
Issue: Trip Creation Functionality Errors

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#767]
**Describe the bug**
When creating a trip, several functionalities encounter errors. After selecting a destination, nearby trails and parks reset upon adding a pack. Additionally, adding items to selected packs fails, and existing packs do not retain added items. Furthermore, newly added packs also face issues with item addition, and previously saved items are not displayed.

**To Reproduce**
1. Visit the URL: https://packrat.world/
2. Log in to your account with the following credentials:
3. Email: zoot3@email.com
4. Password: 12345678
5. Navigate to the main page.
6. Click on the "Create a trip" option, under quick actions.
7. Search for a destination.
8. Select a saved pack from the gear list dropdown.
9. Attempt to add items to the saved pack.

**Expected behavior**
- Nearby trails and parks remain displayed after adding a pack.
- Selection of a saved pack does not reset the destination.
- Maps for the destination appear at the bottom of the screen.
- Users can successfully add items to existing saved packs, and previously saved items are visible.

**Screenshots**

![4](https://github.com/andrew-bierman/PackRat/assets/122357250/03994a83-1e2d-4d60-b376-f0a7e65e7edc)

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by MuhammadHassan03** [comment]
Hello @EngrAJ8888, I have fixed the bugs faced during creating trips. Please check it out on the latest PR.

PR Link : https://github.com/andrew-bierman/PackRat/pull/777

**Comment by EngrAJ8888** [comment]
Hi @MuhammadHassan03, thank you for letting me know! I'll take a look at the pull request to review the fixes.

**Comment by EngrAJ8888** [comment]
Hi @MuhammadHassan03, validated updates in this one.
The saved items in the pack are still encountering issues. Users are unable to view the saved items or add new ones.

![17](https://github.com/andrew-bierman/PackRat/assets/122357250/9aeb84cd-5fe9-4681-95da-aa7304014fed)

**Comment by MuhammadHassan03** [comment]
It is working on my end please check it out once again and wait for around 5-10 seconds (depends upon your internet speed) for server response .....:)
![2](https://github.com/andrew-bierman/PackRat/assets/97297671/27529b7e-b1ae-42f8-a757-e49cd82ad3c4)
![1](https://github.com/andrew-bierman/PackRat/assets/97297671/70b04fc6-3d37-4aff-a583-e8ba8ced352c)

**Comment by EngrAJ8888** [comment]
Still seeing this error
https://github.com/andrew-bierman/PackRat/assets/122357250/ff96e077-190e-4053-944c-93bb96c06562

**Comment by MuhammadHassan03** [comment]
Are you testing it in vite or next?

**Comment by andrew-bierman** [comment]
For reference, I'm experiencing the same as AJ when adding items to a pack during creation of a trip

**Comment by MuhammadHassan03** [comment]
> For reference, I'm experiencing the same as AJ when adding items to a pack during creation of a trip 

Okay, I'll look it once again

**Comment by andrew-bierman** [comment]
> > For reference, I'm experiencing the same as AJ when adding items to a pack during creation of a trip
> 
> Okay, I'll look it once again

Thanks. 

Check on the preview deploys linked at top of this issue. I agree its working in your video, but something questionable is happening on live versions

**Comment by EngrAJ8888** [comment]
> > > For reference, I'm experiencing the same as AJ when adding items to a pack during creation of a trip
> > 
> > 
> > Okay, I'll look it once again
> 
> Thanks.
> 
> Check on the preview deploys linked at top of this issue. I agree its working in your video, but something questionable is happening on live versions

Thank you! I'm using this preview link - https://packrat-dev-qj5h.onrender.com/

**Comment by MuhammadHassan03** [comment]
Hello @EngrAJ8888!

Here is an update into the issue, i have performed checks on the issue and the problem is solved now, please check it out if any other issue left then let me know.

**Comment by EngrAJ8888** [comment]
Hi @MuhammadHassan03 

I'm still encountering the same issues, could you please take another look at the issue. Thank you!

https://github.com/andrew-bierman/PackRat/assets/122357250/2ce278b4-b49a-48a4-9f81-12d6febeaae3

**Comment by EngrAJ8888** [comment]
Hey @taronaleksanian , could you assist with this? there's still an issue when selecting a saved pack. It looks like the items saved to the pack aren't showing up. Thank you!

**Comment by jeweltee** [comment]
the issue on this still persists both on  main and testing branch

**Comment by jeweltee** [comment]
Hi @taronaleksanian I'm still experiencing this issue on the cloud fare link - https://packrat.pages.dev/ 
can you check it out? Thank You

**Comment by EngrAJ8888** [comment]
The issue is being addressed in ticket #852. Closing this one now.
