### ISSUE TITLE
Unable to Access Publicly Shared Trip Owner's Profile

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#772]
**Describe the bug**
Upon attempting to browse shared trips by other users, clicking on their trips and viewing their profile results in an application error.

**To Reproduce**

1. Visit the URL: https://packrat.world/
    same issue here: https://packrat-dev-qj5h.onrender.com
3. Log in to your account with the following credentials:
   Email: zoot3@email.com
   Password: 12345678
6. Navigate to the main page.
7. Click on the “Trips” option
8. Select any Shared Trips from the feed.
9. Attempt to view the profile of the trip owner.

**Expected behavior**
The trip owner's profile should be accessible, displaying their shared trips and packs.

**Screenshots**
![11](https://github.com/andrew-bierman/PackRat/assets/122357250/172ddcc6-7ec4-46e3-a787-a87927abdec6)

**Desktop (please complete the following information):**
 Browser: 
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by pinocchio-life-like** [comment]
Resolved in PR: https://github.com/andrew-bierman/PackRat/pull/781 @EngrAJ8888

**Comment by EngrAJ8888** [comment]
Hi @pinocchio-life-like - still seeing this error. Thanks! 

![15](https://github.com/andrew-bierman/PackRat/assets/122357250/701ca4b5-63b1-4f67-a2ec-ec6a071bbd48)

**Comment by pinocchio-life-like** [comment]
I logged in using [zoot3@email.com](mailto:zoot3@email.com) and access Eliyas's shared trip and see his profile

**Comment by pinocchio-life-like** [comment]
Alright, I will look into it @EngrAJ8888

**Comment by pinocchio-life-like** [comment]
This is fixed now in PR: https://github.com/andrew-bierman/PackRat/pull/788 @EngrAJ8888

**Comment by pinocchio-life-like** [comment]
but now Unable to Access Publicly Shared pack Owner's Profile, I made an oversight in the last PR, and fixing for trip broke the pack owner profile access. 

and this is now solved in PR: https://github.com/andrew-bierman/PackRat/pull/798

**Comment by EngrAJ8888** [comment]
@pinocchio-life-like Thank you! All goods now, closing task.
